adding center parameters for AllSkyAxes
lpsinger/ligo.skymap pull request #26
Opened 2023-11-16 22:27 UTC by swyatt7

Adds the ability to center a mollweide or aitoff projection on given coordinates. 

The `center` parameter follows the same behavior as the zoom and globe projections. It is defaulted to `"180d 0d"` upon init in the `AllSkyAxes` class, and cast into an `astropy.coordinates.SkyCoord`, where the ra and dec are set to the header `"CRVAL1"` and `"CRVAL2"`, respectively.

2023-11-16 23:22 UTC, lpsinger requested changes
- [ ] `180d 0d` is the correct default value for `astro` projections but not `geo` projections — hence the original setting of `'CRVAL1': self._crval1`. Please fix.
- [ ] Please add image comparison tests to `ligo.skymap.plot.tests.test_plot`.

2023-11-29 19:33 UTC, lpsinger requested changes

2023-11-29 19:33 UTC, lpsinger commented on ligo/skymap/plot/tests/test_plot.py
> +    return fig
Add missing newline to end of file.

2023-11-29 19:33 UTC, lpsinger commented on ligo/skymap/plot/allsky.py
> +            h['MJD-OBS'] = Time(obstime).utc.mjd
Why is it necessary to set MJD-OBS in the header?

2023-11-29 19:34 UTC, lpsinger commented
Also, please add a change log entry!

2023-11-29 19:47 UTC, swyatt7 commented on ligo/skymap/plot/allsky.py
> +            h['MJD-OBS'] = Time(obstime).utc.mjd
It suppresses this warning from astropy.wcs:
```
ligo/skymap/plot/tests/test_plot.py: 13 warnings
  /Users/crisp/anaconda3/envs/ligosky/lib/python3.11/site-packages/astropy/wcs/wcs.py:819: FITSFixedWarning: 'datfix' made the change 'Set MJD-OBS to 57982.528524 from DATE-OBS'.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
```

I can revert it back if you see necessary.

2023-11-29 19:48 UTC, swyatt7 commented on ligo/skymap/plot/tests/test_plot.py
> +    return fig
in recent push

2023-11-29 19:55 UTC, lpsinger requested changes

2023-11-29 19:55 UTC, lpsinger commented on CHANGES.rst
> +- Added options to center `mollweide` and `aitoff` projections.
This is reStructuredText, not Markdown:

```suggestion
- Added options to center ``mollweide`` and ``aitoff`` projections.
```

2023-11-29 20:21 UTC, lpsinger commented
This looks great! This is a GitHub mirror of https://git.ligo.org/lscsoft/ligo.skymap/ and the real CI/CD pipeline runs in GitLab, so I pushed this to a branch and opened it as a GitLab MR here: https://git.ligo.org/lscsoft/ligo.skymap/-/merge_requests/343

2023-11-29 20:22 UTC, lpsinger requested changes
Please fix linter errors from https://git.ligo.org/leo-singer/ligo.skymap/-/jobs/3061659.

2023-11-30 00:44 UTC, lpsinger requested changes
Please update this documentation: https://github.com/lpsinger/ligo.skymap/blob/68fca3ddf1e54788fe5ab19bffabe58e987bb2f1/ligo/skymap/plot/allsky.py#L44-L46

2023-12-01 01:07 UTC, lpsinger requested changes
Please fix lint errors: https://git.ligo.org/leo-singer/ligo.skymap/-/jobs/3063950

2023-12-01 22:20 UTC, closed without merging